#!/bin/bash
################################################################################
# Create python new project using Command line in linux systems.
#
# This script is released to the Public Domain by Mina Gabriel
# Mina Ghobrial <minamaged113@gmail.com>
#
# References> https://gist.github.com/11404707.git
################################################################################
set -e
set -u
set -o pipefail

NOACT=0
NAME=$(basename $0|sed 's/\(\..*\)$//')
VERSION="0.1"

: ${VERBOSE:=0}
: ${LOGFILE:="${NAME}.log"}
: ${CONF_FILE:="${NAME}.conf"}
: ${NOACT:=0}

HOSTNAME=`hostname -s`
function version() {
    cat << EOF >&2
$NAME - $VERSION
EOF
}

function copyright(){
    version
    cat << EOCOPYRIGHT >&2
Creates a new Python3 project.
Copyright (C) 2019  Mina Ghobrial

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

EOCOPYRIGHT
}

#################################################################################
# Main body
# Parse options
while getopts ':u:p:c:hn:qvVw' opt; do
	case "$opt" in
	    c) CONF_FILE="$OPTARG" ;;
	    h) usage "Help Requested" ; exit 0;;
        n) 
		CREATE_DIR="$OPTARG"
		echo "$OPTARG" ;;
	    q) VERBOSE=0 ;;
	    v) VERBOSE=$(($VERBOSE+1)) ;;
	    V) version; exit 0;;
	    w) copyright; exit 0;;
	    :) usage "Option -${OPTARG} requires an argument." ; exit 1 ;;
	    \?) usage "Invalid option -${OPTARG}" ; exit 1;;
	esac
done
shift $((OPTIND-1))


# if projectName given, use it. if not, exit.
[[ -n $CREATE_DIR ]] && mkdir $CREATE_DIR && cd $CREATE_DIR
# create src/ directory
mkdir src >> /dev/null
# create __init__.py and main.py inside src/
touch {src/__init__.py,src/main.py}

# create tests/ directory
mkdir tests >> /dev/null

# create __init__.py and test_main.py inside tests/
touch {tests/__init__.py,tests/test_main.py} 

# create README.md and populate
echo "# $CREATE_DIR" >> README.md

# create .gitignore and populate it with
# basic python boilerplate
echo $(curl -s https://gitignore.io/api/python >> .gitignore) > /dev/null

# create python virtual environment
# and install basic packages
python3 -m venv venv >> /dev/null
source venv/bin/activate
pip install wheel >> /dev/null
pip install pylint >> /dev/null
pip install pep8 >> /dev/null
pip install pytest >> /dev/null
pip install pytest-cov >> /dev/null

# create requirements.txt file
touch requirements.txt

# create LICENSE.txt and put GPL v3.0 inside
echo $(curl -s https://git.savannah.gnu.org/cgit/bash.git/plain/COPYING >> LICENSE.txt) > /dev/null


